# Generated by Django 4.2.5 on 2023-10-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_loader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
